<?php
require_once 'System.php';
require_once 'File/Passwd/Common.php';

class File_Passwd_Common_Foo extends File_Passwd_Common {
    function parse() {
        return true;
    }
}
        
        
/**
 * TestCase for File_Passwd_CommonTest class
 * Generated by PHPEdit.XUnit Plugin
 * 
 */
class File_Passwd_CommonTest extends PHPUnit_Framework_TestCase {

    var $pwd;
    protected $exp_file;

    /**
     * Called before the test functions will be executed this function is defined in PHPUnit_Framework_TestCase  and overwritten here
     * @access protected
     */
    function setUp(){
        $this->exp_file = dirname(__FILE__) . '/common.txt';
        $this->pwd = new File_Passwd_Common();
    }
    
    /**
     * Called after the test functions are executed this function is defined in PHPUnit_Framework_TestCase  and overwritten here
     * @access protected
     */
    function tearDown(){
        $this->pwd = null;
    }
    
    /**
     * Regression test for File_Passwd_Common.parse method
     * @access public
     * @expectedException File_Passwd_Exception
     */
    function testparse(){
        $this->pwd->parse();
    }
    
    /**
     * Regression test for File_Passwd_Common.save method
     * @access public
     * @expectedException File_Passwd_Exception
     */
    function testsave(){
        $this->pwd->save();
    }
    
    /**
     * Regression test for File_Passwd_Common.load method
     * @access public
     */
    function testload(){

        $this->exp_file = dirname(__FILE__) . '/common.txt';
        $this->pwd = new File_Passwd_Common_Foo();

        $array = array('1stLine', '2ndLine', '3rdLine');
        $this->pwd->setFile($this->exp_file);
        $this->pwd->load();
        $this->assertEquals($array, $this->pwd->_contents);
    }
    
    /**
     * Regression test for File_Passwd_Common.setFile method
     * @access public
     */
    function testsetFile(){
        $this->pwd->setFile('passwd.file');
        $this->assertEquals('passwd.file', $this->pwd->getFile());
    }
    
    /**
     * Regression test for File_Passwd_Common.getFile method
     * @access public
     */
    function testgetFile(){
        $this->pwd->setFile('passwd.file');
        $this->assertEquals('passwd.file', $this->pwd->getFile());
    }
    
    /**
     * Regression test for File_Passwd_Common.userExists method
     * @access public
     */
    function testuserExists(){
        $this->pwd->_users = array('mike' => array());
        $this->assertTrue($this->pwd->userExists('mike'));
    }
    
    /**
     * Regression test for File_Passwd_Common.delUser method
     * @access public
     */
    function testdelUser(){
        $this->pwd->_users = array('mike' => array('nothing'));
        $this->assertTrue($this->pwd->delUser('mike'));
    }
    
    /**
     * Regression test for File_Passwd_Common.listUser method
     * @access public
     */
    function testlistUser(){
        $array = array('mike' => array('nothing'));
        $this->pwd->_users = $array;
        $this->assertEquals($array, $this->pwd->listUser());
        $this->assertEquals(array('nothing'), $this->pwd->listUser('mike'));
    }
    
    function test_auth(){
        $this->assertEquals('1stLine', File_Passwd_Common::_auth($this->exp_file, '1stLine', ''));
        $this->assertFalse(File_Passwd_Common::_auth($this->exp_file, 'nonexist'));
    }
}